### ISSUE TITLE
Error - Failed to fetch the image list

### ISSUE THREAD

**Issue by PeterRob** [awesometic/odroid-etcher#1]
- Etcher version: 1.7.8-1
- Operating system and architecture: Win 11 x64 
- Image flashed:
- What do you think should have happened: Option 'flash Odroid image'
- What happened: 'Failed to fetch the image list.'
- Do you see any meaningful error information in the DevTools? 'Failed to load resource: net::ERR_FILE_NOT_FOUND'
![Screenshot 2022-05-24 130446](https://user-images.githubusercontent.com/45441478/169953094-bd630d6b-f086-4f27-a41d-438ab3e9f4e7.png)

**Comment by PeterRob** [comment]
I think this was a transient issue with the repository as I can now get the listing. I'll close this.

**Comment by awesometic** [comment]
Sorry for the really late reply. But I'm here to notify you about the repository.

Currently, the device information has been provided using my personal server. Because I quit from AWS service because of the service fee, it was EC2 before but it will be the same in Lambda or something else, so it sometimes would not work if the server is under maintenance.

I'm sorry for this inconvenience, I have a plan to move the repository server to the free hosting one which would be Github I think so it won't be again, I hope.

Thank you for your interest in my work. 😄
